import * as fs from 'fs/promises';
import * as path from 'path';
import { createDeepAgent } from 'deepagents';
import { ChatOpenAI } from '@langchain/openai';
import { tool } from '@langchain/core/tools';
import { z } from 'zod';
import * as dotenv from 'dotenv';

// Load environment variables
dotenv.config();

/**
 * This example demonstrates how to build a DeepAgent that uses 
 * the output of OpenWiki (Code Brain mode) as its context memory.
 */
async function main() {
  console.log("🚀 Starting Code Reviewer DeepAgent...");

  // 1. Simulate reading the OpenWiki documentation
  // In a real scenario, this would be generated by running `openwiki code --init`
  const openWikiDocsPath = path.join(process.cwd(), 'docs');
  let architectureContext = "";
  
  try {
    // We'll read the docs we created earlier as our "Wiki Memory"
    const docPath = path.join(openWikiDocsPath, '03-code-brain.md');
    architectureContext = await fs.readFile(docPath, 'utf-8');
    console.log("✅ Successfully loaded OpenWiki architecture context.");
  } catch (error) {
    console.log("⚠️ Could not find specific wiki file, using default context.");
    architectureContext = "The project uses TypeScript, Node.js, and follows a modular architecture.";
  }

  // 2. Define custom tools for our DeepAgent
  const readSourceCode = tool(
    async ({ filePath }) => {
      try {
        const content = await fs.readFile(filePath, 'utf-8');
        return content;
      } catch (error) {
        return `Error reading file: ${error}`;
      }
    },
    {
      name: "read_source_code",
      description: "Reads the content of a source code file to review it.",
      schema: z.object({
        filePath: z.string().describe("The path to the file to read"),
      }),
    }
  );

  // 3. Create the DeepAgent with OpenWiki context injected into the system prompt
  // We inject the wiki context so the agent doesn't need to discover the architecture from scratch
  const systemPrompt = `
You are an expert Senior Software Engineer and Code Reviewer.
Your goal is to review code changes and ensure they align with the project's architecture.

Here is the Project Architecture and Guidelines (Generated by OpenWiki):
<wiki_context>
${architectureContext}
</wiki_context>

When asked to review code:
1. Read the source code using the provided tools if needed.
2. Compare the implementation against the <wiki_context>.
3. Provide actionable feedback, pointing out architectural violations if any.
`;

  // Initialize the model (ensure OPENAI_API_KEY is in your .env)
  const model = new ChatOpenAI({
    modelName: process.env.OPENAI_MODEL || "gpt-4o-mini",
    temperature: 0.2,
  });

  console.log("🤖 Initializing DeepAgent harness...");
  const agent = await createDeepAgent({
    model: model,
    tools: [readSourceCode],
    systemPrompt: systemPrompt,
  });

  // 4. Run the agent to review a hypothetical code change
  console.log("🔍 Starting code review task...\n");
  
  const result = await agent.invoke({
    messages: [
      {
        role: "user",
        content: "I want to add a new authentication module. Based on our project's wiki, should I use JWT or Sessions? Please explain based on the architecture context provided.",
      },
    ],
  });

  console.log("\n=========================================");
  console.log("📝 AGENT REVIEW RESULT:");
  console.log("=========================================\n");
  
  // Extract and print the final AI response
  const finalMessage = result.messages[result.messages.length - 1];
  console.log(finalMessage.content);
}

main().catch(console.error);
