import * as fs from 'fs/promises';
import * as path from 'path';
import { createDeepAgent } from 'deepagents';
import { ChatOpenAI } from '@langchain/openai';
import { tool } from '@langchain/core/tools';
import { z } from 'zod';
import * as dotenv from 'dotenv';

dotenv.config();

/**
 * Wiki Memory Agent
 * 
 * This agent demonstrates how to build a DeepAgent that:
 * 1. Reads from a local wiki (generated by OpenWiki Personal Brain)
 * 2. Answers questions based on the wiki content
 * 3. Can update the wiki with new information
 * 
 * This is the core pattern behind OpenWiki's Personal Brain mode.
 */

// Custom tool: Search the wiki directory for relevant files
const searchWiki = tool(
  async ({ query }) => {
    const wikiDir = path.join(process.cwd(), 'wiki-output');
    
    try {
      const files = await fs.readdir(wikiDir);
      const mdFiles = files.filter(f => f.endsWith('.md'));
      
      const results: string[] = [];
      
      for (const file of mdFiles) {
        const content = await fs.readFile(path.join(wikiDir, file), 'utf-8');
        if (content.toLowerCase().includes(query.toLowerCase())) {
          results.push(`📄 ${file}:\n${content}\n---`);
        }
      }
      
      if (results.length === 0) {
        return "No relevant wiki entries found for this query.";
      }
      
      return results.join('\n\n');
    } catch (error) {
      return `Wiki directory not found. Run 'npm run cli:ingest' first to populate the wiki.`;
    }
  },
  {
    name: "search_wiki",
    description: "Searches the local wiki directory for entries matching the query. Use this to find relevant context about the user's projects, emails, or saved content.",
    schema: z.object({
      query: z.string().describe("The search term to look for in wiki files"),
    }),
  }
);

// Custom tool: Add a new entry to the wiki
const addToWiki = tool(
  async ({ title, content }) => {
    const wikiDir = path.join(process.cwd(), 'wiki-output');
    
    try {
      await fs.mkdir(wikiDir, { recursive: true });
      
      const filename = title.toLowerCase().replace(/\s+/g, '-') + '.md';
      const filePath = path.join(wikiDir, filename);
      
      const mdContent = `# ${title}\n\n${content}\n\n---\n*Added: ${new Date().toISOString()}*\n`;
      await fs.writeFile(filePath, mdContent);
      
      return `Successfully added "${title}" to the wiki at ${filename}`;
    } catch (error) {
      return `Error adding to wiki: ${error}`;
    }
  },
  {
    name: "add_to_wiki",
    description: "Adds a new entry to the personal wiki. Use this when the user wants to remember something or when you discover important information that should be persisted.",
    schema: z.object({
      title: z.string().describe("Title of the wiki entry"),
      content: z.string().describe("Content of the wiki entry in markdown format"),
    }),
  }
);

// Custom tool: List all wiki entries
const listWikiEntries = tool(
  async () => {
    const wikiDir = path.join(process.cwd(), 'wiki-output');
    
    try {
      const files = await fs.readdir(wikiDir);
      const mdFiles = files.filter(f => f.endsWith('.md'));
      
      if (mdFiles.length === 0) {
        return "The wiki is empty. No entries found.";
      }
      
      return `Wiki entries (${mdFiles.length} files):\n` + mdFiles.map(f => `  - ${f}`).join('\n');
    } catch (error) {
      return "Wiki directory not found. Initialize it first.";
    }
  },
  {
    name: "list_wiki_entries",
    description: "Lists all entries currently stored in the personal wiki.",
    schema: z.object({}),
  }
);

async function main() {
  console.log("🧠 Starting Wiki Memory Agent (powered by DeepAgents)...\n");

  const model = new ChatOpenAI({
    modelName: process.env.OPENAI_MODEL || "gpt-4o-mini",
    temperature: 0.3,
  });

  const agent = await createDeepAgent({
    model: model,
    tools: [searchWiki, addToWiki, listWikiEntries],
    systemPrompt: `
You are a Personal Knowledge Assistant powered by a local wiki memory system.
Your wiki contains information ingested from the user's Gmail, X/Twitter bookmarks, Notion notes, and other sources.

Your capabilities:
1. Search the wiki for relevant information using "search_wiki"
2. Add new knowledge to the wiki using "add_to_wiki"  
3. List all available wiki entries using "list_wiki_entries"

When the user asks a question:
- First, search the wiki for relevant context
- If found, answer based on the wiki content
- If not found, let the user know and offer to add new information

Always be helpful and proactive about suggesting what to remember.
    `,
  });

  // Example interaction
  console.log("📋 Running example queries...\n");

  // Query 1: List what's in the wiki
  console.log("─── Query 1: What's in my brain? ───");
  const result1 = await agent.invoke({
    messages: [{ role: "user", content: "What information do you have in my wiki? List all entries." }],
  });
  const msg1 = result1.messages[result1.messages.length - 1];
  console.log(msg1.content);
  console.log("\n");

  // Query 2: Search for specific topic
  console.log("─── Query 2: Search for projects ───");
  const result2 = await agent.invoke({
    messages: [{ role: "user", content: "What are my active projects?" }],
  });
  const msg2 = result2.messages[result2.messages.length - 1];
  console.log(msg2.content);
  console.log("\n");

  // Query 3: Add new knowledge
  console.log("─── Query 3: Remember something new ───");
  const result3 = await agent.invoke({
    messages: [{ 
      role: "user", 
      content: "Please remember this: I have a meeting with the AI team on Thursday at 3 PM to discuss the DeepAgents integration." 
    }],
  });
  const msg3 = result3.messages[result3.messages.length - 1];
  console.log(msg3.content);
  console.log("\n");
}

main().catch(console.error);
